import { Trade, JournalNote } from "./types";

// Demo trades to show how the dashboard looks with real data.
// These get used when the database is empty so you can see everything working.

const today = new Date();
function daysAgo(n: number) {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function hoursAfter(base: string, h: number) {
  const d = new Date(base);
  d.setHours(d.getHours() + h);
  return d.toISOString();
}

export const DEMO_TRADES: Trade[] = [
  {
    id: "demo-1",
    user_id: "",
    symbol: "BTCUSDT",
    position: "long",
    entry_price: 96200,
    exit_price: 97850,
    quantity: 0.15,
    fees: 4.5,
    open_timestamp: daysAgo(14),
    close_timestamp: hoursAfter(daysAgo(14), 6),
    notes: "Clean breakout above 96k resistance. Held through the pullback.",
    tags: ["breakout", "btc"],
    pnl: (97850 - 96200) * 0.15 - 4.5,
    emotion: "Calm",
    confidence: 8,
    setup_type: "Breakout",
    process_score: 9,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Held through the pullback without panicking", improve: "Could have added to the position at the retest" },
    created_at: daysAgo(14),
  },
  {
    id: "demo-2",
    user_id: "",
    symbol: "ETHUSDT",
    position: "long",
    entry_price: 3420,
    exit_price: 3310,
    quantity: 2,
    fees: 3.2,
    open_timestamp: daysAgo(13),
    close_timestamp: hoursAfter(daysAgo(13), 4),
    notes: "Fakeout. Entered too early before confirmation.",
    tags: ["mistake", "eth"],
    pnl: (3310 - 3420) * 2 - 3.2,
    emotion: "FOMO",
    confidence: 6,
    setup_type: "Breakout",
    process_score: 3,
    checklist: { on_plan: true, stop_loss: true, invalidation: false, not_reacting: false },
    review: { followed_entry_rules: "No", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Respected the stop loss", improve: "Wait for candle close confirmation before entry" },
    created_at: daysAgo(13),
  },
  {
    id: "demo-3",
    user_id: "",
    symbol: "SOLUSDT",
    position: "long",
    entry_price: 185.5,
    exit_price: 198.2,
    quantity: 25,
    fees: 2.8,
    open_timestamp: daysAgo(11),
    close_timestamp: hoursAfter(daysAgo(11), 8),
    notes: "SOL momentum play. Entered on the 4h trend continuation.",
    tags: ["momentum", "sol"],
    pnl: (198.2 - 185.5) * 25 - 2.8,
    emotion: "Confident",
    confidence: 9,
    setup_type: "Trend Follow",
    process_score: 8,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Great entry timing on the pullback", improve: "Could have trailed stop tighter" },
    created_at: daysAgo(11),
  },
  {
    id: "demo-4",
    user_id: "",
    symbol: "BTCUSDT",
    position: "short",
    entry_price: 98100,
    exit_price: 97200,
    quantity: 0.1,
    fees: 3.8,
    open_timestamp: daysAgo(10),
    close_timestamp: hoursAfter(daysAgo(10), 3),
    notes: "Rejection at 98.5k. Shorted the double top.",
    tags: ["reversal", "btc"],
    pnl: (98100 - 97200) * 0.1 - 3.8,
    emotion: "Calm",
    confidence: 7,
    setup_type: "Reversal",
    process_score: 8,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Patient entry at the double top", improve: "Nothing major" },
    created_at: daysAgo(10),
  },
  {
    id: "demo-5",
    user_id: "",
    symbol: "AVAXUSDT",
    position: "long",
    entry_price: 42.8,
    exit_price: 40.1,
    quantity: 50,
    fees: 2.1,
    open_timestamp: daysAgo(9),
    close_timestamp: hoursAfter(daysAgo(9), 5),
    notes: "Caught in a market-wide dump. Should have waited for BTC to stabilize.",
    tags: ["mistake", "avax"],
    pnl: (40.1 - 42.8) * 50 - 2.1,
    emotion: "Anxious",
    confidence: 5,
    setup_type: "Breakout",
    process_score: 4,
    checklist: { on_plan: false, stop_loss: true, invalidation: false, not_reacting: false },
    review: { followed_entry_rules: "No", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Cut the loss quickly", improve: "Check BTC trend before entering alts" },
    created_at: daysAgo(9),
  },
  {
    id: "demo-6",
    user_id: "",
    symbol: "ETHUSDT",
    position: "long",
    entry_price: 3280,
    exit_price: 3450,
    quantity: 3,
    fees: 4.0,
    open_timestamp: daysAgo(7),
    close_timestamp: hoursAfter(daysAgo(7), 12),
    notes: "ETH reclaimed the 200MA. Strong bounce play.",
    tags: ["bounce", "eth"],
    pnl: (3450 - 3280) * 3 - 4.0,
    emotion: "Confident",
    confidence: 8,
    setup_type: "Reversal",
    process_score: 9,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Waited for the 200MA reclaim confirmation", improve: "Size was a bit small for the confidence level" },
    created_at: daysAgo(7),
  },
  {
    id: "demo-7",
    user_id: "",
    symbol: "LINKUSDT",
    position: "long",
    entry_price: 18.5,
    exit_price: 19.8,
    quantity: 100,
    fees: 1.9,
    open_timestamp: daysAgo(6),
    close_timestamp: hoursAfter(daysAgo(6), 7),
    notes: "LINK altseason play. Volume spike on the breakout.",
    tags: ["breakout", "link"],
    pnl: (19.8 - 18.5) * 100 - 1.9,
    emotion: "Excited",
    confidence: 7,
    setup_type: "Breakout",
    process_score: 7,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Good volume confirmation", improve: "Could have let it run a bit more" },
    created_at: daysAgo(6),
  },
  {
    id: "demo-8",
    user_id: "",
    symbol: "BTCUSDT",
    position: "long",
    entry_price: 97800,
    exit_price: 96500,
    quantity: 0.08,
    fees: 3.0,
    open_timestamp: daysAgo(5),
    close_timestamp: hoursAfter(daysAgo(5), 2),
    notes: "Stop loss hit. Entered against the trend.",
    tags: ["mistake", "btc"],
    pnl: (96500 - 97800) * 0.08 - 3.0,
    emotion: "Frustrated",
    confidence: 4,
    setup_type: "Trend Follow",
    process_score: 3,
    checklist: { on_plan: false, stop_loss: true, invalidation: false, not_reacting: false },
    review: { followed_entry_rules: "No", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Respected the stop", improve: "Don't fight the trend. Wait for confirmation." },
    created_at: daysAgo(5),
  },
  {
    id: "demo-9",
    user_id: "",
    symbol: "DOGEUSDT",
    position: "long",
    entry_price: 0.185,
    exit_price: 0.212,
    quantity: 10000,
    fees: 1.5,
    open_timestamp: daysAgo(3),
    close_timestamp: hoursAfter(daysAgo(3), 9),
    notes: "Meme coin pump. Quick scalp, took profits early.",
    tags: ["scalp", "doge"],
    pnl: (0.212 - 0.185) * 10000 - 1.5,
    emotion: "Excited",
    confidence: 6,
    setup_type: "Scalp",
    process_score: 6,
    checklist: { on_plan: false, stop_loss: true, invalidation: false, not_reacting: false },
    review: { followed_entry_rules: "No", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Took profits instead of getting greedy", improve: "This wasn't on my plan — got lucky" },
    created_at: daysAgo(3),
  },
  {
    id: "demo-10",
    user_id: "",
    symbol: "SOLUSDT",
    position: "short",
    entry_price: 202.5,
    exit_price: 195.3,
    quantity: 15,
    fees: 2.5,
    open_timestamp: daysAgo(2),
    close_timestamp: hoursAfter(daysAgo(2), 4),
    notes: "SOL rejection at resistance. Clean short setup.",
    tags: ["reversal", "sol"],
    pnl: (202.5 - 195.3) * 15 - 2.5,
    emotion: "Calm",
    confidence: 8,
    setup_type: "Reversal",
    process_score: 9,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Perfect execution of the plan", improve: "Nothing — this is how every trade should go" },
    created_at: daysAgo(2),
  },
  {
    id: "demo-11",
    user_id: "",
    symbol: "BTCUSDT",
    position: "long",
    entry_price: 98500,
    exit_price: 99200,
    quantity: 0.12,
    fees: 4.2,
    open_timestamp: daysAgo(1),
    close_timestamp: hoursAfter(daysAgo(1), 5),
    notes: "BTC pushing for 100k. Riding the momentum.",
    tags: ["momentum", "btc"],
    pnl: (99200 - 98500) * 0.12 - 4.2,
    emotion: "Confident",
    confidence: 9,
    setup_type: "Trend Follow",
    process_score: 8,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: { followed_entry_rules: "Yes", followed_exit_rules: "Yes", moved_stop: "No", did_well: "Let the winner run", improve: "Could have scaled in more aggressively" },
    created_at: daysAgo(1),
  },
  {
    id: "demo-12",
    user_id: "",
    symbol: "ETHUSDT",
    position: "long",
    entry_price: 3500,
    exit_price: null,
    quantity: 2.5,
    fees: 0,
    open_timestamp: daysAgo(0),
    close_timestamp: null,
    notes: "ETH looking strong. Holding for the move above 3.6k.",
    tags: ["swing", "eth"],
    pnl: null,
    emotion: "Calm",
    confidence: 7,
    setup_type: "Trend Follow",
    process_score: null,
    checklist: { on_plan: true, stop_loss: true, invalidation: true, not_reacting: true },
    review: null,
    created_at: daysAgo(0),
  },
];

export const DEMO_JOURNAL_NOTES: JournalNote[] = [
  {
    id: "demo-note-1",
    user_id: "",
    title: "Week 1 Recap: Finding My Edge",
    content: `<h2>Summary</h2><p>First full week of disciplined journaling. <strong>+$847.30 total P&L</strong> across 8 trades. Win rate sitting at 62.5% which isn't bad, but the real story is in the psychology data.</p><h2>What I learned about myself</h2><ul><li><strong>FOMO is my biggest leak.</strong> The ETH trade (demo-2) cost me $223 because I entered before confirmation. My confidence was only 6/10 — I knew it wasn't clean but entered anyway.</li><li>When I'm <strong>Calm or Confident</strong>, I'm profitable 100% of the time. That's not a coincidence.</li><li>My <strong>off-plan trades</strong> have a ~30% win rate vs ~75% on-plan. The data is screaming: stick to the plan.</li></ul><h2>Goals for next week</h2><ul><li>No trades below 7/10 confidence</li><li>Fill out the pre-trade checklist every single time</li><li>Journal within 30 minutes of closing a trade</li></ul><p><em>The edge isn't in finding better setups. It's in executing the ones I already have.</em></p>`,
    tags: ["weekly-recap", "psychology"],
    trade_id: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: "demo-note-2",
    user_id: "",
    title: "Breakout Setup Playbook",
    content: `<h2>Setup: 4H Range Breakout</h2><p>This is my highest win-rate setup. Documenting the rules so I stop freelancing entries.</p><h2>Entry conditions (ALL must be true)</h2><ul><li>Price consolidating in a clear range for 3+ days</li><li>Volume declining during consolidation (compression)</li><li>BTC not in a downtrend (check 4H and Daily)</li><li><strong>Wait for 4H candle CLOSE above/below range</strong> — no wicks</li><li>Enter on the retest of the breakout level</li></ul><h2>Stop loss</h2><p>Below the opposite side of the range. If range is $96k-$98k and we break up, stop goes at $95.8k (just below range low with buffer).</p><h2>Targets</h2><ul><li><strong>TP1:</strong> 1:1 risk-reward (take 50% off)</li><li><strong>TP2:</strong> Range height projected from breakout (trail stop to entry)</li><li><strong>TP3:</strong> Let runner ride with trailing stop</li></ul><h2>Red flags (DO NOT enter)</h2><ul><li>Major news event in next 4 hours</li><li>BTC at a key resistance/support (likely to reverse)</li><li>Funding rates extreme (>0.05%)</li><li>Your confidence is below 7/10</li></ul><p><em>The BTC breakout on day 1 (demo-1) was a textbook execution of this setup. Process score 9/10, +$247. This is what it looks like when you follow the rules.</em></p>`,
    tags: ["strategy", "breakout", "playbook"],
    trade_id: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(10),
  },
  {
    id: "demo-note-3",
    user_id: "",
    title: "FOMO Trade Post-Mortem: ETHUSDT",
    content: `<h2>What happened</h2><p>ETH was pumping. I saw the candle going green and jumped in at $3,420 without waiting for the 4H close. It was a fakeout — price reversed hard and I got stopped at $3,310 for a <strong>-$223.20 loss</strong>.</p><h2>What I felt</h2><p>Classic FOMO. Saw the green candle, felt like I was missing the move. Heart rate went up, palms got sweaty. I recognized it as FOMO <em>while it was happening</em> but entered anyway. That's the worst part.</p><h2>What the rule says</h2><p>My breakout playbook rule #4: <strong>"Wait for 4H candle CLOSE above range — no wicks."</strong> I broke this rule. The candle hadn't closed. It was just a wick into the range high.</p><h2>What I'll do differently</h2><ul><li>Set alerts at levels instead of staring at charts</li><li>If I feel FOMO, close the chart and wait 15 minutes</li><li>Before every entry: read my checklist out loud</li><li>Process score check: if I can't honestly give it a 7+, don't enter</li></ul><p><strong>Cost of this lesson: $223.20.</strong> If I learn from it, it's the cheapest tuition I'll ever pay.</p>`,
    tags: ["mistake", "psychology", "eth", "fomo"],
    trade_id: null,
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
  },
  {
    id: "demo-note-4",
    user_id: "",
    title: "Morning Routine Checklist",
    content: `<h2>Pre-session routine (before opening any chart)</h2><ul><li>Check BTC daily and 4H trend direction</li><li>Review open interest and funding rates</li><li>Check economic calendar for high-impact events</li><li>Review yesterday's trades and journal notes</li><li>Set today's max loss limit: <strong>$500</strong></li><li>Set today's max trades: <strong>3</strong></li></ul><h2>Before every trade</h2><ul><li>Is this on my watchlist/plan?</li><li>What's my exact stop loss? (write the number)</li><li>What would make this trade wrong?</li><li>Am I trading my plan or reacting to price?</li><li>Confidence check: is it 7+ out of 10?</li></ul><h2>After every trade</h2><ul><li>Log it in Stargate immediately</li><li>Rate process score honestly (1-10)</li><li>Tag emotion state</li><li>Write one sentence: what did I learn?</li></ul><p><em>Discipline is doing the boring thing when the exciting thing is calling your name. This checklist is the boring thing. It's also the edge.</em></p>`,
    tags: ["routine", "discipline", "checklist"],
    trade_id: null,
    created_at: daysAgo(14),
    updated_at: daysAgo(14),
  },
];
