/**
 * Comprehensive US stock ticker registry for autocomplete search.
 * Each entry: [ticker, companyName]
 * Sorted alphabetically by ticker for binary search compatibility.
 */

export interface StockEntry {
  ticker: string;
  name: string;
}

// ~500 most commonly traded US stocks/ETFs covering all major sectors
const STOCK_DATA: [string, string][] = [
  // Index ETFs & Popular ETFs
  ["ARKK", "ARK Innovation ETF"],
  ["DIA", "SPDR Dow Jones Industrial Avg ETF"],
  ["EEM", "iShares MSCI Emerging Markets ETF"],
  ["EFA", "iShares MSCI EAFE ETF"],
  ["GDX", "VanEck Gold Miners ETF"],
  ["GLD", "SPDR Gold Shares"],
  ["HYG", "iShares High Yield Corporate Bond ETF"],
  ["IWM", "iShares Russell 2000 ETF"],
  ["IYR", "iShares US Real Estate ETF"],
  ["JNUG", "Direxion Daily Junior Gold Miners Bull 2X"],
  ["KRE", "SPDR S&P Regional Banking ETF"],
  ["LQD", "iShares Investment Grade Corp Bond ETF"],
  ["QQQ", "Invesco QQQ Trust"],
  ["SCHD", "Schwab US Dividend Equity ETF"],
  ["SLV", "iShares Silver Trust"],
  ["SMH", "VanEck Semiconductor ETF"],
  ["SOXL", "Direxion Daily Semiconductor Bull 3X"],
  ["SOXS", "Direxion Daily Semiconductor Bear 3X"],
  ["SPY", "SPDR S&P 500 ETF Trust"],
  ["SPXL", "Direxion Daily S&P 500 Bull 3X"],
  ["TQQQ", "ProShares UltraPro QQQ"],
  ["TLT", "iShares 20+ Year Treasury Bond ETF"],
  ["USO", "United States Oil Fund"],
  ["UVXY", "ProShares Ultra VIX Short-Term Futures"],
  ["VGT", "Vanguard Information Technology ETF"],
  ["VNQ", "Vanguard Real Estate ETF"],
  ["VOO", "Vanguard S&P 500 ETF"],
  ["VTI", "Vanguard Total Stock Market ETF"],
  ["XBI", "SPDR S&P Biotech ETF"],
  ["XLE", "Energy Select Sector SPDR"],
  ["XLF", "Financial Select Sector SPDR"],
  ["XLI", "Industrial Select Sector SPDR"],
  ["XLK", "Technology Select Sector SPDR"],
  ["XLP", "Consumer Staples Select Sector SPDR"],
  ["XLU", "Utilities Select Sector SPDR"],
  ["XLV", "Health Care Select Sector SPDR"],
  ["XLY", "Consumer Discretionary Select Sector SPDR"],
  // Mega Cap Tech
  ["AAPL", "Apple Inc."],
  ["ABNB", "Airbnb Inc."],
  ["ADBE", "Adobe Inc."],
  ["ADI", "Analog Devices Inc."],
  ["ADP", "Automatic Data Processing Inc."],
  ["ADSK", "Autodesk Inc."],
  ["AFRM", "Affirm Holdings Inc."],
  ["AKAM", "Akamai Technologies Inc."],
  ["AMAT", "Applied Materials Inc."],
  ["AMD", "Advanced Micro Devices Inc."],
  ["AMGN", "Amgen Inc."],
  ["AMZN", "Amazon.com Inc."],
  ["ANET", "Arista Networks Inc."],
  ["ANSS", "ANSYS Inc."],
  ["APP", "AppLovin Corporation"],
  ["ARM", "Arm Holdings plc"],
  ["ASML", "ASML Holding N.V."],
  ["ASTS", "AST SpaceMobile Inc."],
  ["AVGO", "Broadcom Inc."],
  ["AZN", "AstraZeneca plc"],
  // B
  ["BA", "Boeing Company"],
  ["BABA", "Alibaba Group Holding"],
  ["BAC", "Bank of America Corp."],
  ["BIDU", "Baidu Inc."],
  ["BIIB", "Biogen Inc."],
  ["BK", "Bank of New York Mellon Corp."],
  ["BKNG", "Booking Holdings Inc."],
  ["BLK", "BlackRock Inc."],
  ["BMY", "Bristol-Myers Squibb Co."],
  ["BRK.B", "Berkshire Hathaway Inc."],
  ["BSX", "Boston Scientific Corp."],
  ["BTI", "British American Tobacco"],
  ["BX", "Blackstone Inc."],
  ["BYND", "Beyond Meat Inc."],
  // C
  ["C", "Citigroup Inc."],
  ["CAT", "Caterpillar Inc."],
  ["CCL", "Carnival Corporation"],
  ["CDNS", "Cadence Design Systems"],
  ["CEG", "Constellation Energy Group"],
  ["CELH", "Celsius Holdings Inc."],
  ["CF", "CF Industries Holdings"],
  ["CHTR", "Charter Communications Inc."],
  ["CI", "Cigna Group"],
  ["CL", "Colgate-Palmolive Co."],
  ["CLF", "Cleveland-Cliffs Inc."],
  ["CMCSA", "Comcast Corporation"],
  ["CME", "CME Group Inc."],
  ["CMG", "Chipotle Mexican Grill"],
  ["CNC", "Centene Corp."],
  ["COIN", "Coinbase Global Inc."],
  ["COP", "ConocoPhillips"],
  ["COST", "Costco Wholesale Corp."],
  ["CPRT", "Copart Inc."],
  ["CRM", "Salesforce Inc."],
  ["CRSP", "CRISPR Therapeutics"],
  ["CRWD", "CrowdStrike Holdings Inc."],
  ["CSCO", "Cisco Systems Inc."],
  ["CTAS", "Cintas Corporation"],
  ["CTSH", "Cognizant Technology Solutions"],
  ["CVS", "CVS Health Corp."],
  ["CVX", "Chevron Corp."],
  // D
  ["D", "Dominion Energy Inc."],
  ["DAL", "Delta Air Lines Inc."],
  ["DASH", "DoorDash Inc."],
  ["DD", "DuPont de Nemours Inc."],
  ["DE", "Deere & Company"],
  ["DELL", "Dell Technologies Inc."],
  ["DFS", "Discover Financial Services"],
  ["DG", "Dollar General Corp."],
  ["DHR", "Danaher Corp."],
  ["DIS", "Walt Disney Company"],
  ["DKNG", "DraftKings Inc."],
  ["DLTR", "Dollar Tree Inc."],
  ["DNB", "Dun & Bradstreet Holdings"],
  ["DOW", "Dow Inc."],
  ["DT", "Dynatrace Inc."],
  ["DUK", "Duke Energy Corp."],
  ["DUOL", "Duolingo Inc."],
  ["DVN", "Devon Energy Corp."],
  // E
  ["EA", "Electronic Arts Inc."],
  ["EBAY", "eBay Inc."],
  ["ECL", "Ecolab Inc."],
  ["EL", "Estee Lauder Companies"],
  ["EMR", "Emerson Electric Co."],
  ["ENPH", "Enphase Energy Inc."],
  ["EOG", "EOG Resources Inc."],
  ["EPAM", "EPAM Systems Inc."],
  ["EQT", "EQT Corporation"],
  ["ESTC", "Elastic N.V."],
  ["ETSY", "Etsy Inc."],
  ["EVRG", "Evergy Inc."],
  ["EW", "Edwards Lifesciences Corp."],
  ["EXPE", "Expedia Group Inc."],
  ["EXR", "Extra Space Storage Inc."],
  // F
  ["F", "Ford Motor Company"],
  ["FANG", "Diamondback Energy Inc."],
  ["FAST", "Fastenal Company"],
  ["FCX", "Freeport-McMoRan Inc."],
  ["FDX", "FedEx Corp."],
  ["FI", "Fiserv Inc."],
  ["FICO", "Fair Isaac Corporation"],
  ["FIS", "Fidelity National Information Services"],
  ["FISV", "Fiserv Inc."],
  ["FIVE", "Five Below Inc."],
  ["FSLR", "First Solar Inc."],
  ["FTNT", "Fortinet Inc."],
  // G
  ["GD", "General Dynamics Corp."],
  ["GE", "GE Aerospace"],
  ["GILD", "Gilead Sciences Inc."],
  ["GIS", "General Mills Inc."],
  ["GLW", "Corning Inc."],
  ["GM", "General Motors Company"],
  ["GOOG", "Alphabet Inc. Class C"],
  ["GOOGL", "Alphabet Inc. Class A"],
  ["GPN", "Global Payments Inc."],
  ["GS", "Goldman Sachs Group Inc."],
  // H
  ["HAL", "Halliburton Company"],
  ["HCA", "HCA Healthcare Inc."],
  ["HD", "Home Depot Inc."],
  ["HIMS", "Hims & Hers Health Inc."],
  ["HLT", "Hilton Worldwide Holdings"],
  ["HON", "Honeywell International Inc."],
  ["HPE", "Hewlett Packard Enterprise"],
  ["HPQ", "HP Inc."],
  ["HSY", "Hershey Company"],
  ["HTHT", "H World Group Limited"],
  ["HUM", "Humana Inc."],
  // I
  ["IBM", "International Business Machines"],
  ["ICE", "Intercontinental Exchange Inc."],
  ["IDXX", "IDEXX Laboratories Inc."],
  ["ILMN", "Illumina Inc."],
  ["INCY", "Incyte Corporation"],
  ["INTC", "Intel Corporation"],
  ["INTU", "Intuit Inc."],
  ["IOT", "Samsara Inc."],
  ["IONQ", "IonQ Inc."],
  ["ISRG", "Intuitive Surgical Inc."],
  ["ITW", "Illinois Tool Works Inc."],
  // J
  ["JBL", "Jabil Inc."],
  ["JCI", "Johnson Controls International"],
  ["JD", "JD.com Inc."],
  ["JNPR", "Juniper Networks Inc."],
  ["JNJ", "Johnson & Johnson"],
  ["JPM", "JPMorgan Chase & Co."],
  // K
  ["K", "Kellanova"],
  ["KDP", "Keurig Dr Pepper Inc."],
  ["KHC", "Kraft Heinz Company"],
  ["KLAC", "KLA Corporation"],
  ["KKR", "KKR & Co. Inc."],
  ["KMB", "Kimberly-Clark Corp."],
  ["KMI", "Kinder Morgan Inc."],
  ["KO", "Coca-Cola Company"],
  ["KR", "Kroger Co."],
  // L
  ["LCID", "Lucid Group Inc."],
  ["LDOS", "Leidos Holdings Inc."],
  ["LEN", "Lennar Corp."],
  ["LHX", "L3Harris Technologies Inc."],
  ["LI", "Li Auto Inc."],
  ["LIN", "Linde plc"],
  ["LLY", "Eli Lilly and Company"],
  ["LMT", "Lockheed Martin Corp."],
  ["LOW", "Lowe's Companies Inc."],
  ["LRCX", "Lam Research Corp."],
  ["LULU", "Lululemon Athletica Inc."],
  ["LUV", "Southwest Airlines Co."],
  ["LVS", "Las Vegas Sands Corp."],
  ["LYFT", "Lyft Inc."],
  // M
  ["MA", "Mastercard Inc."],
  ["MAR", "Marriott International Inc."],
  ["MCD", "McDonald's Corp."],
  ["MCHP", "Microchip Technology Inc."],
  ["MCK", "McKesson Corp."],
  ["MCO", "Moody's Corporation"],
  ["MDLZ", "Mondelez International Inc."],
  ["MDT", "Medtronic plc"],
  ["MELI", "MercadoLibre Inc."],
  ["MET", "MetLife Inc."],
  ["META", "Meta Platforms Inc."],
  ["MGM", "MGM Resorts International"],
  ["MKC", "McCormick & Company"],
  ["MNST", "Monster Beverage Corp."],
  ["MO", "Altria Group Inc."],
  ["MOFT", "Microsoft Corp."],
  ["MOH", "Molina Healthcare Inc."],
  ["MPC", "Marathon Petroleum Corp."],
  ["MPLX", "MPLX LP"],
  ["MRNA", "Moderna Inc."],
  ["MRVL", "Marvell Technology Inc."],
  ["MS", "Morgan Stanley"],
  ["MSCI", "MSCI Inc."],
  ["MSFT", "Microsoft Corp."],
  ["MSI", "Motorola Solutions Inc."],
  ["MSTR", "MicroStrategy Inc."],
  ["MU", "Micron Technology Inc."],
  // N
  ["NCLH", "Norwegian Cruise Line Holdings"],
  ["NEE", "NextEra Energy Inc."],
  ["NEM", "Newmont Corp."],
  ["NET", "Cloudflare Inc."],
  ["NFLX", "Netflix Inc."],
  ["NIO", "NIO Inc."],
  ["NKE", "Nike Inc."],
  ["NOC", "Northrop Grumman Corp."],
  ["NOW", "ServiceNow Inc."],
  ["NSC", "Norfolk Southern Corp."],
  ["NTAP", "NetApp Inc."],
  ["NTES", "NetEase Inc."],
  ["NU", "Nu Holdings Ltd."],
  ["NUE", "Nucor Corp."],
  ["NVAX", "Novavax Inc."],
  ["NVDA", "NVIDIA Corporation"],
  ["NVO", "Novo Nordisk A/S"],
  ["NXPI", "NXP Semiconductors N.V."],
  // O
  ["O", "Realty Income Corp."],
  ["OKE", "ONEOK Inc."],
  ["ON", "ON Semiconductor Corp."],
  ["ORCL", "Oracle Corp."],
  ["OSTK", "Overstock.com Inc."],
  ["OXY", "Occidental Petroleum Corp."],
  // P
  ["PANW", "Palo Alto Networks Inc."],
  ["PATH", "UiPath Inc."],
  ["PARA", "Paramount Global"],
  ["PAYC", "Paycom Software Inc."],
  ["PAYX", "Paychex Inc."],
  ["PBR", "Petrobras"],
  ["PCAR", "PACCAR Inc."],
  ["PDD", "PDD Holdings Inc."],
  ["PEP", "PepsiCo Inc."],
  ["PFE", "Pfizer Inc."],
  ["PG", "Procter & Gamble Co."],
  ["PGR", "Progressive Corp."],
  ["PH", "Parker-Hannifin Corp."],
  ["PHM", "PulteGroup Inc."],
  ["PINS", "Pinterest Inc."],
  ["PLTR", "Palantir Technologies Inc."],
  ["PM", "Philip Morris International"],
  ["PNC", "PNC Financial Services Group"],
  ["PODD", "Insulet Corporation"],
  ["PSA", "Public Storage"],
  ["PSX", "Phillips 66"],
  ["PXD", "Pioneer Natural Resources Co."],
  ["PYPL", "PayPal Holdings Inc."],
  // Q
  ["QCOM", "Qualcomm Inc."],
  ["QRVO", "Qorvo Inc."],
  // R
  ["RCL", "Royal Caribbean Cruises"],
  ["REGN", "Regeneron Pharmaceuticals"],
  ["RIVN", "Rivian Automotive Inc."],
  ["RKLB", "Rocket Lab USA Inc."],
  ["ROKU", "Roku Inc."],
  ["ROK", "Rockwell Automation Inc."],
  ["ROP", "Roper Technologies Inc."],
  ["ROST", "Ross Stores Inc."],
  ["RSP", "Invesco S&P 500 Equal Weight ETF"],
  ["RTX", "RTX Corporation"],
  // S
  ["S", "SentinelOne Inc."],
  ["SBUX", "Starbucks Corp."],
  ["SCHW", "Charles Schwab Corp."],
  ["SE", "Sea Limited"],
  ["SEDG", "SolarEdge Technologies"],
  ["SHOP", "Shopify Inc."],
  ["SHW", "Sherwin-Williams Co."],
  ["SIRI", "Sirius XM Holdings"],
  ["SLB", "SLB (Schlumberger)"],
  ["SMCI", "Super Micro Computer Inc."],
  ["SNAP", "Snap Inc."],
  ["SNOW", "Snowflake Inc."],
  ["SNPS", "Synopsys Inc."],
  ["SO", "Southern Company"],
  ["SOFI", "SoFi Technologies Inc."],
  ["SPG", "Simon Property Group Inc."],
  ["SPGI", "S&P Global Inc."],
  ["SQ", "Block Inc."],
  ["SRE", "Sempra"],
  ["STLD", "Steel Dynamics Inc."],
  ["STX", "Seagate Technology Holdings"],
  ["STZ", "Constellation Brands Inc."],
  ["SWK", "Stanley Black & Decker"],
  ["SWKS", "Skyworks Solutions Inc."],
  ["SYK", "Stryker Corp."],
  ["SYY", "Sysco Corp."],
  // T
  ["T", "AT&T Inc."],
  ["TAP", "Molson Coors Beverage Co."],
  ["TDG", "TransDigm Group Inc."],
  ["TEAM", "Atlassian Corporation"],
  ["TECK", "Teck Resources Limited"],
  ["TER", "Teradyne Inc."],
  ["TFC", "Truist Financial Corp."],
  ["TGT", "Target Corp."],
  ["TJX", "TJX Companies Inc."],
  ["TMO", "Thermo Fisher Scientific"],
  ["TMUS", "T-Mobile US Inc."],
  ["TPR", "Tapestry Inc."],
  ["TRMB", "Trimble Inc."],
  ["TSLA", "Tesla Inc."],
  ["TSM", "Taiwan Semiconductor Manufacturing"],
  ["TSN", "Tyson Foods Inc."],
  ["TT", "Trane Technologies plc"],
  ["TTD", "The Trade Desk Inc."],
  ["TTWO", "Take-Two Interactive Software"],
  ["TWLO", "Twilio Inc."],
  ["TXN", "Texas Instruments Inc."],
  ["TXT", "Textron Inc."],
  // U
  ["U", "Unity Software Inc."],
  ["UAL", "United Airlines Holdings"],
  ["UBER", "Uber Technologies Inc."],
  ["UNH", "UnitedHealth Group Inc."],
  ["UNP", "Union Pacific Corp."],
  ["UPS", "United Parcel Service Inc."],
  ["URI", "United Rentals Inc."],
  ["USB", "U.S. Bancorp"],
  ["ULTA", "Ulta Beauty Inc."],
  // V
  ["V", "Visa Inc."],
  ["VALE", "Vale S.A."],
  ["VFC", "V.F. Corporation"],
  ["VICI", "VICI Properties Inc."],
  ["VLO", "Valero Energy Corp."],
  ["VMC", "Vulcan Materials Company"],
  ["VRSK", "Verisk Analytics Inc."],
  ["VRSN", "VeriSign Inc."],
  ["VRTX", "Vertex Pharmaceuticals Inc."],
  ["VRT", "Vertiv Holdings Co."],
  ["VST", "Vistra Corp."],
  ["VZ", "Verizon Communications Inc."],
  // W
  ["W", "Wayfair Inc."],
  ["WBA", "Walgreens Boots Alliance"],
  ["WBD", "Warner Bros. Discovery"],
  ["WDC", "Western Digital Corp."],
  ["WDAY", "Workday Inc."],
  ["WEC", "WEC Energy Group Inc."],
  ["WELL", "Welltower Inc."],
  ["WFC", "Wells Fargo & Company"],
  ["WM", "Waste Management Inc."],
  ["WMB", "Williams Companies Inc."],
  ["WMT", "Walmart Inc."],
  ["WOLF", "Wolfspeed Inc."],
  // X
  ["X", "United States Steel Corp."],
  ["XOM", "Exxon Mobil Corp."],
  ["XPEV", "XPeng Inc."],
  // Y
  ["YINN", "Direxion Daily FTSE China Bull 3X"],
  ["YUM", "Yum! Brands Inc."],
  // Z
  ["Z", "Zillow Group Inc."],
  ["ZIM", "ZIM Integrated Shipping"],
  ["ZM", "Zoom Video Communications"],
  ["ZS", "Zscaler Inc."],
  ["ZTO", "ZTO Express Inc."],
];

// Build lookup structures
export const STOCK_LIST: StockEntry[] = STOCK_DATA.map(([ticker, name]) => ({
  ticker,
  name,
}));

// Fast lookup by ticker
const STOCK_MAP = new Map(STOCK_DATA.map(([ticker, name]) => [ticker, name]));

export function resolveStockName(ticker: string): string | undefined {
  return STOCK_MAP.get(ticker.toUpperCase());
}

// Popular quick-access symbols per page context
export const POPULAR_STOCKS: Record<string, string[]> = {
  "options-flow": ["SPY", "QQQ", "AAPL", "TSLA", "NVDA", "META", "AMZN", "AMD", "COIN", "SMCI"],
  fundamentals: ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "TSLA", "META", "JPM", "V", "UNH"],
  "options-simulator": ["AAPL", "TSLA", "NVDA", "SPY", "QQQ", "META", "AMZN", "AMD", "MSFT", "COIN"],
  "options-backtest": ["SPY", "QQQ", "AAPL", "TSLA", "NVDA", "AMZN", "META", "GOOGL", "MSFT", "NFLX"],
};

// Search function — matches ticker prefix first, then name substring
export function searchStocks(query: string, limit = 12): StockEntry[] {
  if (!query) return [];
  const q = query.toUpperCase();
  const results: StockEntry[] = [];
  const seen = new Set<string>();

  // Pass 1: exact ticker match
  for (const entry of STOCK_LIST) {
    if (entry.ticker === q) {
      results.push(entry);
      seen.add(entry.ticker);
      break;
    }
  }

  // Pass 2: ticker prefix match
  for (const entry of STOCK_LIST) {
    if (results.length >= limit) break;
    if (!seen.has(entry.ticker) && entry.ticker.startsWith(q)) {
      results.push(entry);
      seen.add(entry.ticker);
    }
  }

  // Pass 3: name substring match
  const qLower = query.toLowerCase();
  for (const entry of STOCK_LIST) {
    if (results.length >= limit) break;
    if (!seen.has(entry.ticker) && entry.name.toLowerCase().includes(qLower)) {
      results.push(entry);
      seen.add(entry.ticker);
    }
  }

  return results;
}
