// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(simulator)/simulator/multi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulator/multi">> = Specific
  const handler = {} as typeof import("../../src/app/(simulator)/simulator/multi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(simulator)/simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulator">> = Specific
  const handler = {} as typeof import("../../src/app/(simulator)/simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/achievements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/achievements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ai">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/fees">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/running-pnl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/running-pnl">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/running-pnl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/sectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/sectors">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/sectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/tag-groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/tag-groups">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/tag-groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/technical-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/technical-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/technical-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/trade-count/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/trade-count">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/trade-count/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/treemap/sector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/treemap/sector">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/treemap/sector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/treemap/symbol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/treemap/symbol">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/treemap/symbol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/treemap/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/treemap/tags">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/treemap/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analysis/volume/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analysis/volume">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analysis/volume/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/backtester/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/backtester">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/backtester/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/compare-trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/compare-trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/compare-trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/filters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/filters">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/filters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/multi-simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/multi-simulator">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/multi-simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/options-backtest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/options-backtest">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/options-backtest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/options-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/options-flow">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/options-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/options-payoff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/options-payoff">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/options-payoff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/options-simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/options-simulator">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/options-simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/pnl-charts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/pnl-charts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/pnl-charts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/seasonality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/seasonality">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/seasonality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/sec-13f/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/sec-13f">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/sec-13f/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/shared-trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/shared-trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/shared-trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/stock-screener/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/stock-screener">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/stock-screener/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/target-simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/apps/target-simulator">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/target-simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendar/day/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar/day">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendar/day/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendar/week/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar/week">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendar/week/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendar/year/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar/year">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendar/year/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/commodities/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/commodities/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/commodities/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/commodities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/commodities">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/commodities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/commodities/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/commodities/plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/commodities/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/commodities/trades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/commodities/trades/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/commodities/trades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/commodities/trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/commodities/trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/commodities/trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/dca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/dca">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/dca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/execution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/execution">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/execution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/exit-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exit-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/exit-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/forex/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/forex/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/forex/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/forex/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/forex">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/forex/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/forex/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/forex/plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/forex/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/forex/trades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/forex/trades/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/forex/trades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/forex/trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/forex/trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/forex/trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/funding-rates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funding-rates">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/funding-rates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/goals">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/heatmaps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/heatmaps">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/heatmaps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/help">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/insights">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/journal">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/market">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/expectancy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/expectancy">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/expectancy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/hit-ratio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/hit-ratio">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/hit-ratio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/mfe-mae/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/mfe-mae">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/mfe-mae/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/profit-factor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/profit-factor">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/profit-factor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/r-value/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/r-value">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/r-value/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/returns">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/trends/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/trends">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/trends/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/performance/volume/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance/volume">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/performance/volume/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/playbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/playbook">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/playbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/prop-firm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/prop-firm">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/prop-firm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/risk-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/risk-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/risk-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/risk">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/rules">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/screener/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/screener">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/screener/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/simulations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/simulations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/simulations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/statistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/statistics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/statistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks/market">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/options-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks/options-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/options-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks/plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/trades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks/trades/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/trades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stocks/trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stocks/trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stocks/trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/summaries/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/summaries/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/summaries/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/summaries/open-trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/summaries/open-trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/summaries/open-trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/summaries/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/summaries/tags">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/summaries/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/taxes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/taxes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/taxes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/chart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/chart">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/chart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/day-grouped/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/day-grouped">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/day-grouped/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/executions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/executions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/executions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/goals">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/pivot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/pivot">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/pivot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/plan-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/plan-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/plan-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/symbol-grouped/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/symbol-grouped">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/symbol-grouped/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/tag-grouped/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/trades/tag-grouped">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/tag-grouped/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/providers">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/trade-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/trade-summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/trade-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invite/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invite/redeem">> = Specific
  const handler = {} as typeof import("../../src/app/api/invite/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/fundamentals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/fundamentals">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/fundamentals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/funding-rates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/funding-rates">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/funding-rates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/historical/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/historical">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/historical/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/options-flow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/options-flow">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/options-flow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/screener/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/screener">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/screener/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/seasonality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/seasonality">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/seasonality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/sec-13f/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/sec-13f">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/sec-13f/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/stock-screener/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/stock-screener">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/stock-screener/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/stocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/stocks">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/stocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trades/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trades/share">> = Specific
  const handler = {} as typeof import("../../src/app/api/trades/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(simulator)/simulator/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/simulator">> = Specific
  const handler = {} as typeof import("../../src/app/(simulator)/simulator/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/apps/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/apps">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/apps/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/calendar/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/calendar/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/trades/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/trades">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/trades/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
