import type { BrokerInstruction } from "@/lib/import-export-types";

export const BROKER_INSTRUCTIONS: BrokerInstruction[] = [
  // ═══ Crypto Exchanges ═══
  {
    brokerId: "binance",
    brokerName: "Binance",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Binance account",
      "Navigate to Orders > Trade History",
      "Select your preferred date range",
      "Click 'Export' and choose CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV (UTF-8)",
    expectedColumns: ["Date(UTC)", "Pair", "Side", "Price", "Executed", "Amount", "Fee"],
    notes: [
      "Binance exports in UTC timezone by default",
      "Futures trades are separate — export from the Futures section",
      "US users: Use Binance.US, not Binance.com",
    ],
    apiKeyGuide: {
      steps: [
        "Log into Binance → hover over your profile icon → 'API Management'",
        "Click 'Create API' → select 'System Generated Keys'",
        "Enter a label (e.g., 'Journal Sync') and complete 2FA verification",
        "On the API restrictions page, check only 'Enable Reading'",
        "Under 'Enable Futures', check the box (needed to read futures trade history)",
        "Copy the API Key and Secret Key — the secret is only shown once",
      ],
      permissions: ["Enable Reading", "Enable Futures (read only)"],
      notes: [
        "Never enable 'Enable Trading' or 'Enable Withdrawals'",
        "IP whitelist is recommended — add your IP for extra security",
        "Binance does not require a passphrase",
      ],
    },
  },
  {
    brokerId: "bybit",
    brokerName: "Bybit",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bybit account",
      "Go to Assets > Trade History",
      "Select Spot, Derivatives, or USDC tab",
      "Set your date range and click 'Export CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Avg Entry Price", "Avg Exit Price", "Order Qty", "Closed PnL", "Exec Fee"],
    notes: [
      "Bybit separates Spot and Derivatives exports",
      "For derivatives, use the 'Closed PnL' section for completed trades",
    ],
    apiKeyGuide: {
      steps: [
        "Log into Bybit → click your profile icon → 'API'",
        "Click 'Create New Key' → select 'System-Generated API Keys'",
        "Set a name (e.g., 'Journal Sync') and complete 2FA",
        "Under 'API Key Permissions', select 'Read-Only'",
        "Under 'Unified Trading permissions', enable 'Read' for Derivatives",
        "Copy the API Key and Secret Key — the secret is shown only once",
      ],
      permissions: ["Read-Only", "Derivatives Read"],
      notes: [
        "Never enable 'Read-Write' or 'Contract Trade' permissions",
        "Bybit does not require a passphrase",
        "You can restrict to IP whitelist for extra security",
      ],
    },
  },
  {
    brokerId: "okx",
    brokerName: "OKX",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your OKX account",
      "Go to Assets > Order History",
      "Select the trading type (Spot, Margin, Futures, etc.)",
      "Click the Export button and choose CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Inst ID", "Side", "Avg Px", "Fill Px", "Fill Sz", "Fee"],
    notes: [
      "OKX uses 'Inst ID' for trading pair (e.g., BTC-USDT)",
      "Export each trading type separately for best results",
    ],
    apiKeyGuide: {
      steps: [
        "Log into OKX → hover over profile icon → 'API' under Security",
        "Click 'Create API key' (V5 API)",
        "Set a label and passphrase, complete 2FA",
        "Under Permissions, select 'Read' only",
        "Under 'Trade' section, enable 'Read' for the account types you trade (Futures, etc.)",
        "Copy the API Key, Secret Key, and passphrase",
      ],
      permissions: ["Read", "Trade Read (Futures)"],
      notes: [
        "OKX requires a passphrase (similar to Bitget)",
        "Never enable 'Trade' or 'Withdraw' write permissions",
        "IP whitelist is optional but recommended",
      ],
    },
  },
  {
    brokerId: "coinbase",
    brokerName: "Coinbase",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Coinbase account",
      "Go to Taxes > Documents (or Reports)",
      "Click 'Generate Report' and select Transaction History",
      "Choose CSV format and download",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Timestamp", "Transaction Type", "Asset", "Quantity", "Spot Price at Transaction", "Subtotal"],
    notes: [
      "Coinbase includes buys, sells, sends, and receives in one export",
      "Filter to 'Buy' and 'Sell' transactions for trade imports",
      "Coinbase Pro/Advanced exports have different column names",
    ],
  },
  {
    brokerId: "kraken",
    brokerName: "Kraken",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Kraken account",
      "Go to History > Export",
      "Select 'Trades' as the export type",
      "Set your date range and click 'Submit'",
      "Download the CSV and upload here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["txid", "ordertxid", "pair", "type", "price", "vol", "cost", "fee", "margin"],
    notes: [
      "Kraken uses 'vol' for volume/quantity",
      "Pair names may use X/Z prefixes (e.g., XXBTZUSD for BTC/USD)",
    ],
    apiKeyGuide: {
      steps: [
        "Log into Kraken → click your name (top right) → 'Security' → 'API'",
        "Click 'Create API Key'",
        "Set a description (e.g., 'Journal Sync')",
        "Under Permissions, enable only 'Query Funds' and 'Query Open/Closed Orders and Trades'",
        "Do NOT enable any 'Modify' or 'Create/Cancel' permissions",
        "Click 'Generate Key' and copy both the API Key and Private Key",
      ],
      permissions: ["Query Funds", "Query Open/Closed Orders and Trades"],
      notes: [
        "Kraken uses granular permissions — only enable the 'Query' ones",
        "Kraken does not require a passphrase",
        "The Private Key is only shown once — save it securely",
      ],
    },
  },
  {
    brokerId: "kucoin",
    brokerName: "KuCoin",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your KuCoin account",
      "Go to Orders > Trade History",
      "Select Spot or Futures tab",
      "Click 'Export' and set your date range",
      "Upload the downloaded CSV here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Deal Price", "Deal Size", "Fee", "Time"],
    notes: [
      "KuCoin exports Spot and Futures separately",
      "Date range is limited to 3 months per export",
    ],
  },
  {
    brokerId: "gateio",
    brokerName: "Gate.io",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Gate.io account",
      "Go to Orders > Trade History",
      "Click 'Export' in the top right",
      "Select CSV format and date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Pair", "Side", "Filled Price", "Filled Amount", "Filled Total", "Fee"],
    notes: ["Gate.io limits exports to 3 months at a time"],
  },
  {
    brokerId: "bitget",
    brokerName: "Bitget",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bitget account",
      "On the left side, click on 'Orders' then select the asset type you trade",
      "Click on the 'Orders' tab, then click 'Export data' on the right side",
      "Select your preferred date range",
      "Upload the downloaded file here (CSV or Excel)",
    ],
    fileFormat: "CSV or Excel (.xlsx)",
    expectedColumns: ["Date", "Direction", "Coin", "Price", "Average Price", "Executed", "Realized P/L", "NetProfits"],
    notes: [
      "Bitget may export as Excel (.xlsx) — both formats are supported",
      "The 'Executed' column maps to trade quantity (filled amount)",
      "'Direction' values like 'Buy/Long' and 'Sell/Short' are auto-detected",
      "Alternative: Go to Order History and navigate to 'Future Trades', select 'Export'",
    ],
    apiKeyGuide: {
      steps: [
        "Log into Bitget → click your profile icon (top right) → 'API Management'",
        "Click 'Create API Key' → choose 'System-Generated'",
        "Enter a label (e.g., 'Journal Sync')",
        "Create a passphrase — you'll need this when connecting (Bitget won't show it again!)",
        "Under Permissions, select 'Read-Only'",
        "Under API permissions, enable only 'Futures' → check 'Read'",
        "Do NOT enable 'Trade', 'Transfer', or 'Withdraw'",
        "Click 'Next', complete 2FA, then copy your API Key and Secret Key",
      ],
      permissions: ["Read-Only", "Futures → Read"],
      notes: [
        "The passphrase is created by YOU — remember it! Bitget won't show it again after creation",
        "Never enable 'Trade' or 'Withdraw' — the journal only reads your trade history",
        "IP whitelist is optional but adds extra security",
        "If you lose your passphrase, delete the API key and create a new one",
      ],
    },
  },
  {
    brokerId: "mexc",
    brokerName: "MEXC",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your MEXC account",
      "Go to Orders > Trade History",
      "Click 'Export' and set your date range",
      "Download the CSV file",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Trade Price", "Filled Qty", "Trade Fee", "Time"],
    notes: ["MEXC export format is similar to Bitget"],
  },
  {
    brokerId: "htx",
    brokerName: "HTX (Huobi)",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your HTX account",
      "Go to Orders > Trade History",
      "Click 'Export' button",
      "Select CSV format and date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Trade Price", "Filled Qty", "Trade Fee", "Time"],
    notes: ["HTX was formerly known as Huobi Global"],
  },
  {
    brokerId: "cryptocom",
    brokerName: "Crypto.com",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Crypto.com account",
      "Go to Accounts > Transaction History",
      "Click 'Export' and choose CSV",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Timestamp (UTC)", "Transaction Description", "Currency", "Amount", "To Currency", "To Amount", "Native Amount"],
    notes: [
      "Crypto.com includes all transaction types (trades, deposits, withdrawals, rewards)",
      "Filter to trade transactions for best results",
    ],
  },
  {
    brokerId: "gemini",
    brokerName: "Gemini",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Gemini account",
      "Go to Account > Balances",
      "Click 'Download History' at the top right",
      "Select your date range and format (CSV)",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Type", "Symbol", "Amount", "Price", "Fee"],
    notes: ["Gemini includes both buys and sells in the history export"],
  },
  {
    brokerId: "bitstamp",
    brokerName: "Bitstamp",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bitstamp account",
      "Go to Transactions",
      "Click 'Export' button",
      "Select CSV and your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Type", "Datetime", "Amount", "Value", "Rate", "Fee"],
    notes: ["Bitstamp exports include all transaction types — filter to trades"],
  },

  {
    brokerId: "binanceus",
    brokerName: "Binance.US",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Binance.US account",
      "Go to Orders > Trade History",
      "Select your date range",
      "Click 'Export' and choose CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV (UTF-8)",
    expectedColumns: ["Date(UTC)", "Pair", "Side", "Price", "Executed", "Amount", "Fee"],
    notes: [
      "Binance.US is the US-regulated version of Binance",
      "Export format is identical to Binance.com",
    ],
  },
  {
    brokerId: "bitfinex",
    brokerName: "Bitfinex",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bitfinex account",
      "Go to Reports > Trades",
      "Set your date range",
      "Click 'Export CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["#", "PAIR", "AMOUNT", "PRICE", "FEE", "FEE CURRENCY", "DATE"],
    notes: [
      "Bitfinex uses signed amounts — negative means sell",
      "Margin trades and funding are in separate reports",
    ],
  },
  {
    brokerId: "phemex",
    brokerName: "Phemex",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Phemex account",
      "Go to Orders > Trade History",
      "Select Spot or Contract tab",
      "Click 'Export' and set your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Exec Price", "Exec Qty", "Exec Value", "Fee", "Time"],
    notes: [
      "Phemex separates Spot and Contract exports",
      "Contract trades include leverage information",
    ],
  },
  {
    brokerId: "bingx",
    brokerName: "BingX",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your BingX account",
      "Go to Orders > Trade History",
      "Select your trading type (Spot/Futures)",
      "Click 'Export' and choose CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Price", "Quantity", "Fee", "Time"],
    notes: [
      "BingX supports Spot, Perpetual Futures, and Copy Trading exports",
    ],
  },
  {
    brokerId: "dydx",
    brokerName: "dYdX",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Connect your wallet to dYdX",
      "Go to Portfolio > History",
      "Click 'Export' to download trade history",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Market", "Side", "Size", "Price", "Fee", "Created At"],
    notes: [
      "dYdX v4 runs on its own Cosmos chain",
      "All trades are perpetual futures",
    ],
  },

  // ═══ Stock Brokers ═══
  {
    brokerId: "robinhood",
    brokerName: "Robinhood",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Robinhood account (web)",
      "Go to Account > Statements & History",
      "Click 'Download CSV' for your transaction history",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Activity Date", "Instrument", "Side", "Quantity", "Average Price", "Amount"],
    notes: [
      "Robinhood exports include stocks and options together",
      "Options trades will include contract details",
    ],
  },
  {
    brokerId: "schwab",
    brokerName: "Charles Schwab",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Schwab account",
      "Go to Accounts > History",
      "Set your date range and filter to 'Trades'",
      "Click 'Export' to download as CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Action", "Symbol", "Quantity", "Price", "Fees & Comm", "Amount"],
    notes: [
      "After the TD Ameritrade merger, older trades may be in a different format",
      "Filter to 'Buy' and 'Sell' actions for cleaner imports",
    ],
  },
  {
    brokerId: "ibkr",
    brokerName: "Interactive Brokers",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into IBKR Client Portal or TWS",
      "Go to Reports > Activity Statements",
      "Select your date range",
      "Choose CSV format and generate the report",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Date/Time", "Quantity", "T. Price", "Comm/Fee", "Realized P/L"],
    notes: [
      "IBKR Activity Statements are very detailed — the 'Trades' section is what you need",
      "Supports stocks, options, futures, and forex in one export",
    ],
  },
  {
    brokerId: "webull",
    brokerName: "Webull",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Webull account (web or app)",
      "Go to Orders > History",
      "Click the download/export button",
      "Select CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Quantity", "Avg Price", "Total", "Status"],
    notes: ["Make sure to export only 'Filled' orders for accurate trade data"],
  },
  {
    brokerId: "fidelity",
    brokerName: "Fidelity",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Fidelity account",
      "Go to Activity & Orders",
      "Click 'Download' at the top of the page",
      "Select CSV format and date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Run Date", "Action", "Symbol", "Quantity", "Price", "Commission", "Amount"],
    notes: ["Fidelity includes dividends and transfers — filter to 'Buy' and 'Sell' for trades"],
  },
  {
    brokerId: "etrade",
    brokerName: "E*Trade",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your E*Trade account",
      "Go to Accounts > Transactions",
      "Click 'Download' in the top right",
      "Select CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["TransactionDate", "TransactionType", "Symbol", "Quantity", "Price", "Commission", "NetAmount"],
    notes: ["E*Trade is now part of Morgan Stanley"],
  },

  {
    brokerId: "tastytrade",
    brokerName: "Tastytrade",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Tastytrade account",
      "Go to History > Transactions",
      "Set your date range",
      "Click 'Export CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Type", "Action", "Symbol", "Quantity", "Average Price", "Commission", "Net Cash"],
    notes: [
      "Tastytrade (formerly Tastyworks) exports include options and equities together",
      "Filter to 'Trade' type for buy/sell transactions",
    ],
  },
  {
    brokerId: "alpaca",
    brokerName: "Alpaca",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Alpaca dashboard",
      "Go to Paper/Live > Activity",
      "Click 'Download' to export as CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["symbol", "side", "qty", "avg_price", "type", "filled_at", "commission"],
    notes: [
      "Alpaca is an API-first broker — CSV export is also available from the dashboard",
      "Column names use snake_case",
      "Supports both paper and live trading exports",
    ],
  },
  {
    brokerId: "moomoo",
    brokerName: "Moomoo",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Moomoo account (web or app)",
      "Go to Trade > Order History",
      "Select your date range and filter to 'Filled'",
      "Click 'Export' to download as CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Filled Qty", "Avg Price", "Commission", "Date"],
    notes: [
      "Moomoo (Futu) supports US, HK, SG, and AU markets",
      "Make sure to export only 'Filled' orders",
    ],
  },

  // ═══ DEX / Blockchain ═══
  {
    brokerId: "etherscan",
    brokerName: "Etherscan",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to Etherscan.io and search for your wallet address",
      "Navigate to the 'Transactions' or 'Token Transfers' tab",
      "Click 'Download CSV Export' at the bottom of the page",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Txhash", "DateTime", "From", "To", "Value", "TokenName", "TokenSymbol"],
    notes: [
      "Etherscan includes all transactions, not just trades",
      "DEX swap transactions will be auto-detected",
      "Gas fees are included in the transaction data",
    ],
  },
  {
    brokerId: "solscan",
    brokerName: "Solscan",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to Solscan.io and search for your wallet address",
      "Go to the Account > Export Transactions tab",
      "Select your date range",
      "Click 'Export CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Signature", "DateTime", "Action", "From", "To", "Amount", "Token"],
    notes: [
      "Solscan exports include all SPL token transfers",
      "Jupiter/Raydium swaps will be auto-detected",
    ],
  },
  {
    brokerId: "zerion",
    brokerName: "Zerion",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Log into your Zerion account",
      "Go to History tab",
      "Click 'Export to CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Type", "Token In", "Amount In", "Token Out", "Amount Out", "Network", "Fee"],
    notes: [
      "Zerion aggregates trades across all connected wallets",
      "Multi-chain transactions are included",
    ],
  },
  {
    brokerId: "arbiscan",
    brokerName: "Arbiscan",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to Arbiscan.io and search for your wallet address",
      "Navigate to the 'Transactions' or 'Token Transfers' tab",
      "Click 'Download CSV Export' at the bottom",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Txhash", "DateTime", "From", "To", "Value", "TokenName", "TokenSymbol"],
    notes: [
      "Arbiscan covers the Arbitrum L2 network",
      "Export format is identical to Etherscan",
      "GMX, Camelot, and other Arbitrum DEX swaps are included",
    ],
  },
  {
    brokerId: "bscscan",
    brokerName: "BscScan",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to BscScan.com and search for your wallet address",
      "Navigate to the 'BEP-20 Token Txns' tab",
      "Click 'Download CSV Export' at the bottom",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Txhash", "DateTime", "From", "To", "Value", "TokenName", "TokenSymbol"],
    notes: [
      "BscScan covers the BNB Smart Chain (BSC)",
      "PancakeSwap and other BSC DEX swaps are included",
      "Export format is identical to Etherscan",
    ],
  },
  {
    brokerId: "debank",
    brokerName: "DeBank",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to DeBank.com and connect or search your wallet",
      "Go to the History tab",
      "Click 'Export' to download your transaction history",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Time", "Chain", "Type", "Token In", "Amount In", "Token Out", "Amount Out", "Fee"],
    notes: [
      "DeBank aggregates transactions across 200+ chains",
      "Swaps are automatically identified and labeled",
      "Pro account may be required for full CSV export",
    ],
  },

  // ═══ Forex Brokers ═══
  {
    brokerId: "metatrader",
    brokerName: "MetaTrader 4/5",
    group: "forex",
    targetTable: "forex_trades",
    steps: [
      "Open MetaTrader 4 or MetaTrader 5",
      "Go to the 'Account History' tab at the bottom",
      "Right-click on the history and select your period (All History, Last 3 Months, etc.)",
      "Right-click again and select 'Save as Detailed Report'",
      "Upload the saved HTML/CSV file here",
    ],
    fileFormat: "CSV or HTML",
    expectedColumns: ["Open Time", "Type", "Symbol", "Volume", "Open Price", "Close Price", "Commission", "Swap", "Profit"],
    notes: [
      "MT4/MT5 works with most forex brokers (IC Markets, Pepperstone, XM, etc.)",
      "The 'Detailed Report' gives the most complete trade data",
      "Swap fees and commissions are included separately",
    ],
  },
  {
    brokerId: "oanda",
    brokerName: "OANDA",
    group: "forex",
    targetTable: "forex_trades",
    steps: [
      "Log into your OANDA account",
      "Go to My Account > Statement & Reports",
      "Select 'Trade History' report type",
      "Set your date range and click 'Download CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Ticket", "Open Date", "Close Date", "Symbol", "Side", "Units", "Open Price", "Close Price", "P/L"],
    notes: [
      "OANDA uses 'Units' instead of lots",
      "P/L is shown in the account's base currency",
    ],
  },
  {
    brokerId: "ig",
    brokerName: "IG Markets",
    group: "forex",
    targetTable: "forex_trades",
    steps: [
      "Log into your IG account",
      "Go to My IG > History",
      "Select 'Transactions' tab",
      "Set your date range and click 'Download' (CSV)",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Reference", "Market", "Direction", "Size", "Opening", "Closing", "P&L"],
    notes: [
      "IG supports forex, indices, commodities, and shares",
      "Spread bet and CFD trades may have different column formats",
      "Available in UK, EU, AU, and other regions",
    ],
  },
];

export function getBrokerInstruction(brokerId: string): BrokerInstruction | undefined {
  return BROKER_INSTRUCTIONS.find((b) => b.brokerId === brokerId);
}

export function getBrokersByGroup(group: "cex" | "stocks" | "dex" | "forex"): BrokerInstruction[] {
  return BROKER_INSTRUCTIONS.filter((b) => b.group === group);
}
