import type { BrokerInstruction } from "@/lib/import-export-types";

export const BROKER_INSTRUCTIONS: BrokerInstruction[] = [
  // ═══ Crypto Exchanges ═══
  {
    brokerId: "binance",
    brokerName: "Binance",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Binance account",
      "Navigate to Orders > Trade History",
      "Select your preferred date range",
      "Click 'Export' and choose CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV (UTF-8)",
    expectedColumns: ["Date(UTC)", "Pair", "Side", "Price", "Executed", "Amount", "Fee"],
    notes: [
      "Binance exports in UTC timezone by default",
      "Futures trades are separate — export from the Futures section",
      "US users: Use Binance.US, not Binance.com",
    ],
  },
  {
    brokerId: "bybit",
    brokerName: "Bybit",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bybit account",
      "Go to Assets > Trade History",
      "Select Spot, Derivatives, or USDC tab",
      "Set your date range and click 'Export CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Avg Entry Price", "Avg Exit Price", "Order Qty", "Closed PnL", "Exec Fee"],
    notes: [
      "Bybit separates Spot and Derivatives exports",
      "For derivatives, use the 'Closed PnL' section for completed trades",
    ],
  },
  {
    brokerId: "okx",
    brokerName: "OKX",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your OKX account",
      "Go to Assets > Order History",
      "Select the trading type (Spot, Margin, Futures, etc.)",
      "Click the Export button and choose CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Inst ID", "Side", "Avg Px", "Fill Px", "Fill Sz", "Fee"],
    notes: [
      "OKX uses 'Inst ID' for trading pair (e.g., BTC-USDT)",
      "Export each trading type separately for best results",
    ],
  },
  {
    brokerId: "coinbase",
    brokerName: "Coinbase",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Coinbase account",
      "Go to Taxes > Documents (or Reports)",
      "Click 'Generate Report' and select Transaction History",
      "Choose CSV format and download",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Timestamp", "Transaction Type", "Asset", "Quantity", "Spot Price at Transaction", "Subtotal"],
    notes: [
      "Coinbase includes buys, sells, sends, and receives in one export",
      "Filter to 'Buy' and 'Sell' transactions for trade imports",
      "Coinbase Pro/Advanced exports have different column names",
    ],
  },
  {
    brokerId: "kraken",
    brokerName: "Kraken",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Kraken account",
      "Go to History > Export",
      "Select 'Trades' as the export type",
      "Set your date range and click 'Submit'",
      "Download the CSV and upload here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["txid", "ordertxid", "pair", "type", "price", "vol", "cost", "fee", "margin"],
    notes: [
      "Kraken uses 'vol' for volume/quantity",
      "Pair names may use X/Z prefixes (e.g., XXBTZUSD for BTC/USD)",
    ],
  },
  {
    brokerId: "kucoin",
    brokerName: "KuCoin",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your KuCoin account",
      "Go to Orders > Trade History",
      "Select Spot or Futures tab",
      "Click 'Export' and set your date range",
      "Upload the downloaded CSV here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Deal Price", "Deal Size", "Fee", "Time"],
    notes: [
      "KuCoin exports Spot and Futures separately",
      "Date range is limited to 3 months per export",
    ],
  },
  {
    brokerId: "gateio",
    brokerName: "Gate.io",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Gate.io account",
      "Go to Orders > Trade History",
      "Click 'Export' in the top right",
      "Select CSV format and date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Pair", "Side", "Filled Price", "Filled Amount", "Filled Total", "Fee"],
    notes: ["Gate.io limits exports to 3 months at a time"],
  },
  {
    brokerId: "bitget",
    brokerName: "Bitget",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bitget account",
      "On the left side, click on 'Orders' then select the asset type you trade",
      "Click on the 'Orders' tab, then click 'Export data' on the right side",
      "Select your preferred date range",
      "Upload the downloaded file here (CSV or Excel)",
    ],
    fileFormat: "CSV or Excel (.xlsx)",
    expectedColumns: ["Date", "Direction", "Coin", "Price", "Average Price", "Executed", "Realized P/L", "NetProfits"],
    notes: [
      "Bitget may export as Excel (.xlsx) — both formats are supported",
      "The 'Executed' column maps to trade quantity (filled amount)",
      "'Direction' values like 'Buy/Long' and 'Sell/Short' are auto-detected",
      "Alternative: Go to Order History and navigate to 'Future Trades', select 'Export'",
    ],
  },
  {
    brokerId: "mexc",
    brokerName: "MEXC",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your MEXC account",
      "Go to Orders > Trade History",
      "Click 'Export' and set your date range",
      "Download the CSV file",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Trade Price", "Filled Qty", "Trade Fee", "Time"],
    notes: ["MEXC export format is similar to Bitget"],
  },
  {
    brokerId: "htx",
    brokerName: "HTX (Huobi)",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your HTX account",
      "Go to Orders > Trade History",
      "Click 'Export' button",
      "Select CSV format and date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Trade Price", "Filled Qty", "Trade Fee", "Time"],
    notes: ["HTX was formerly known as Huobi Global"],
  },
  {
    brokerId: "cryptocom",
    brokerName: "Crypto.com",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Crypto.com account",
      "Go to Accounts > Transaction History",
      "Click 'Export' and choose CSV",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Timestamp (UTC)", "Transaction Description", "Currency", "Amount", "To Currency", "To Amount", "Native Amount"],
    notes: [
      "Crypto.com includes all transaction types (trades, deposits, withdrawals, rewards)",
      "Filter to trade transactions for best results",
    ],
  },
  {
    brokerId: "gemini",
    brokerName: "Gemini",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Gemini account",
      "Go to Account > Balances",
      "Click 'Download History' at the top right",
      "Select your date range and format (CSV)",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Type", "Symbol", "Amount", "Price", "Fee"],
    notes: ["Gemini includes both buys and sells in the history export"],
  },
  {
    brokerId: "bitstamp",
    brokerName: "Bitstamp",
    group: "cex",
    targetTable: "trades",
    steps: [
      "Log into your Bitstamp account",
      "Go to Transactions",
      "Click 'Export' button",
      "Select CSV and your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Type", "Datetime", "Amount", "Value", "Rate", "Fee"],
    notes: ["Bitstamp exports include all transaction types — filter to trades"],
  },

  // ═══ Stock Brokers ═══
  {
    brokerId: "robinhood",
    brokerName: "Robinhood",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Robinhood account (web)",
      "Go to Account > Statements & History",
      "Click 'Download CSV' for your transaction history",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Activity Date", "Instrument", "Side", "Quantity", "Average Price", "Amount"],
    notes: [
      "Robinhood exports include stocks and options together",
      "Options trades will include contract details",
    ],
  },
  {
    brokerId: "schwab",
    brokerName: "Charles Schwab",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Schwab account",
      "Go to Accounts > History",
      "Set your date range and filter to 'Trades'",
      "Click 'Export' to download as CSV",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Action", "Symbol", "Quantity", "Price", "Fees & Comm", "Amount"],
    notes: [
      "After the TD Ameritrade merger, older trades may be in a different format",
      "Filter to 'Buy' and 'Sell' actions for cleaner imports",
    ],
  },
  {
    brokerId: "ibkr",
    brokerName: "Interactive Brokers",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into IBKR Client Portal or TWS",
      "Go to Reports > Activity Statements",
      "Select your date range",
      "Choose CSV format and generate the report",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Date/Time", "Quantity", "T. Price", "Comm/Fee", "Realized P/L"],
    notes: [
      "IBKR Activity Statements are very detailed — the 'Trades' section is what you need",
      "Supports stocks, options, futures, and forex in one export",
    ],
  },
  {
    brokerId: "webull",
    brokerName: "Webull",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Webull account (web or app)",
      "Go to Orders > History",
      "Click the download/export button",
      "Select CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Symbol", "Side", "Quantity", "Avg Price", "Total", "Status"],
    notes: ["Make sure to export only 'Filled' orders for accurate trade data"],
  },
  {
    brokerId: "fidelity",
    brokerName: "Fidelity",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your Fidelity account",
      "Go to Activity & Orders",
      "Click 'Download' at the top of the page",
      "Select CSV format and date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Run Date", "Action", "Symbol", "Quantity", "Price", "Commission", "Amount"],
    notes: ["Fidelity includes dividends and transfers — filter to 'Buy' and 'Sell' for trades"],
  },
  {
    brokerId: "etrade",
    brokerName: "E*Trade",
    group: "stocks",
    targetTable: "stock_trades",
    steps: [
      "Log into your E*Trade account",
      "Go to Accounts > Transactions",
      "Click 'Download' in the top right",
      "Select CSV format",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["TransactionDate", "TransactionType", "Symbol", "Quantity", "Price", "Commission", "NetAmount"],
    notes: ["E*Trade is now part of Morgan Stanley"],
  },

  // ═══ DEX / Blockchain ═══
  {
    brokerId: "etherscan",
    brokerName: "Etherscan",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to Etherscan.io and search for your wallet address",
      "Navigate to the 'Transactions' or 'Token Transfers' tab",
      "Click 'Download CSV Export' at the bottom of the page",
      "Select your date range",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Txhash", "DateTime", "From", "To", "Value", "TokenName", "TokenSymbol"],
    notes: [
      "Etherscan includes all transactions, not just trades",
      "DEX swap transactions will be auto-detected",
      "Gas fees are included in the transaction data",
    ],
  },
  {
    brokerId: "solscan",
    brokerName: "Solscan",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Go to Solscan.io and search for your wallet address",
      "Go to the Account > Export Transactions tab",
      "Select your date range",
      "Click 'Export CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Signature", "DateTime", "Action", "From", "To", "Amount", "Token"],
    notes: [
      "Solscan exports include all SPL token transfers",
      "Jupiter/Raydium swaps will be auto-detected",
    ],
  },
  {
    brokerId: "zerion",
    brokerName: "Zerion",
    group: "dex",
    targetTable: "trades",
    steps: [
      "Log into your Zerion account",
      "Go to History tab",
      "Click 'Export to CSV'",
      "Upload the downloaded file here",
    ],
    fileFormat: "CSV",
    expectedColumns: ["Date", "Type", "Token In", "Amount In", "Token Out", "Amount Out", "Network", "Fee"],
    notes: [
      "Zerion aggregates trades across all connected wallets",
      "Multi-chain transactions are included",
    ],
  },
];

export function getBrokerInstruction(brokerId: string): BrokerInstruction | undefined {
  return BROKER_INSTRUCTIONS.find((b) => b.brokerId === brokerId);
}

export function getBrokersByGroup(group: "cex" | "stocks" | "dex" | "forex"): BrokerInstruction[] {
  return BROKER_INSTRUCTIONS.filter((b) => b.group === group);
}
